github.com:
    users:
        natimerry:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: natimerry
