github.com:
    users:
        natimerry:
            oauth_token: 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
    git_protocol: https
    user: natimerry
    oauth_token: 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
