github.com:
    users:
        natimerry:
            oauth_token: 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
    git_protocol: https
    user: natimerry
    oauth_token: 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
