COMMON_FLAGS="-O3 -march=native -mtune=native -pipe -flto=auto -falign-functions=32 -falign-loops=32"


CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"


CC="clang"
CPP="clang-cpp" # necessary for xorg-server and possibly other packages
CXX="clang++"
AR="llvm-ar"
NM="llvm-nm"
RANLIB="llvm-ranlib"


RUSTFLAGS="${RUSTFLAGS} -C target-cpu=native -C opt-level=3 -C debuginfo=0 -C codegen-units=1"
export LDFLAGS="-fuse-ld=mold --rtlib=libgcc --unwindlib=libgcc"


MAKEOPTS="-j12"
FEATURES="parallel-fetch"
EMERGE_DEFAULT_OPTS="--ask"

ACCEPT_KEYWORDS="~amd64"

VIDEO_CARDS="amdgpu radeonsi"
INPUT_DEVICES="libinput"

USE="X wayland dbus pipewire vulkan opengl \
x264 pdf jpeg png zstd git clang llvm \
qt6 elogind networkmanager pipewire \
-a52 -css -systemd -aqua -ios -ipod -emacs -xemacs -emboss -3dfx -cups -ibm -kde -gnome alsa pulseaudio -bindist -accessibility"

LC_MESSAGES=C.UTF-8
ACCEPT_LICENSE="*"
