theme = "onedark"
[editor]
line-number = "relative"
cursorline = true
color-modes = true
bufferline="multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[keys.normal]
C-b = ":sh make"
C-r = ":sh make run"
